# Date: 2025-06-01
# https://github.com/jellystrm/deceptarr
services:
  deceptarr:
    image: ghcr.io/jellystrm/deceptarr:latest
    container_name: deceptarr
    network_mode: host
    environment:
      # Optional: Only set if you want to override auto-detected values
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      # Config directory - all settings stored here
      - /appdata/deceptarr:/config
      
      # Download folder - must match Radarr/Sonarr download path
      - /srv/mergerfs/MainPool/downloads:/downloads
      
      # Movie/Series library paths - must match Jellyfin library paths
      - /srv/mergerfs/MainPool/Phim:/movies
      - "/srv/mergerfs/MainPool/Phim/TV Shows:/series"
      
    restart: unless-stopped